/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List run headers (newest first)
         * @description Light-weight listing for the Dashboard. Returns run headers sorted
         *     newest-first; no events are joined (call `GET /runs/{run_id}` for depth).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Max rows to return (default 20, capped at 200). */
                    limit?: number;
                    /** @description Filter by run status. */
                    status?: "queued" | "running" | "done" | "failed" | "cancelled";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunList"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProblemInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get run state + event history
         * @description Returns the run header plus a bounded page of audit events ordered by
         *     `seq`. Page with `?after_seq=<next_after_seq>` until `has_more` is false.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Return events with `seq` strictly greater than this cursor. Omit to start from the beginning. */
                    after_seq?: number;
                    /** @description Max events to return (default 5000, hard cap 5000). */
                    limit?: number;
                };
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/finetune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue a paper fine-tune (PaperEditor) request
         * @description The worker loads the run's paper.md + notebook.ipynb and runs
         *     PaperEditorAgent against the natural-language `message`. Events stream
         *     back on the same `mm:events:<run_id>` channel tagged `kind: finetune.*`.
         *     `session_id` is taken from the request (to resume a thread) or minted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FinetuneRequest"];
                };
            };
            responses: {
                /** @description Accepted (queued) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinetuneAccepted"];
                    };
                };
                /** @description Empty message */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signal the worker to halt the run
         * @description Idempotent: re-posting while a cancel is already pending is a no-op.
         *     The worker polls `mm:cancel:<run_id>` between stages and terminates with
         *     `done.status = cancelled`, keeping partial artifacts intact.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted (cancel signalled) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CancelAccepted"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/paper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve the Writer's paper.md for a run
         * @description Returns `<RUNS_DIR>/<run_id>/paper.md`. `?inline=1` renders in-browser
         *     (`Content-Disposition: inline`) for the on-page preview; omitted forces
         *     a download.
         */
        get: {
            parameters: {
                query?: {
                    /** @description When true, serve inline for preview instead of as an attachment. */
                    inline?: boolean;
                };
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/markdown": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (path traversal) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/export/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the paper as md / tex / pdf / docx
         * @description Renders the run's `paper.meta.json` (and `paper.md`) through the
         *     competition LaTeX template and returns the requested format as an
         *     attachment. `md` is served directly without templating.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Override the LaTeX template; defaults to the run's competition type. */
                    template?: "mcm" | "icm" | "cumcm" | "huashu";
                };
                header?: never;
                path: {
                    run_id: string;
                    /** @description Output format. */
                    format: "md" | "tex" | "pdf" | "docx";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/markdown": string;
                        "application/x-tex": string;
                        "application/pdf": string;
                        "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run or paper artifacts not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unsupported format/template, or invalid paper.meta.json */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build a competition submission ZIP bundle
         * @description Assembles the per-competition submission archive from the run's
         *     `paper.meta.json`. MCM/ICM produce a single PDF + README + archival
         *     source; CUMCM/Huashu produce the anonymous + printed PDFs plus a nested
         *     `支撑材料.zip` (notebook + code + figures) per competition spec.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Override the bundle layout; defaults to the run's competition type. */
                    template?: "mcm" | "icm" | "cumcm" | "huashu";
                };
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run or paper.meta.json not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bundle exceeds the size cap */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unsupported template or invalid paper.meta.json */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/figures/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a figure file written by the worker
         * @description Returns the PNG / JPEG / SVG written at
         *     `<RUNS_DIR>/<run_id>/figures/<path>`. Path traversal is rejected
         *     (403). Only image extensions are served (415 for anything else).
         *     Response has `Cache-Control: private, max-age=3600`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                    /** @description Relative path under the run's `figures/` directory. */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                        "image/jpeg": string;
                        "image/svg+xml": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (path traversal) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Payload too large (>16 MiB) */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unsupported media type */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/notebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the executed Jupyter notebook for a run
         * @description Returns `<RUNS_DIR>/<run_id>/notebook.ipynb` as an attachment with
         *     `Content-Type: application/x-ipynb+json`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-ipynb+json": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completions (passthrough to configured providers)
         * @description Body mirrors OpenAI's chat/completions schema. When `stream=true` returns SSE.
         *     Set `X-Run-Id` and `X-Agent` headers so the gateway tags cost accounting and
         *     fans tokens into the matching WS run stream.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Run-Id"?: string;
                    "X-Agent"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline run counts + latency/cost percentiles */
        get: {
            parameters: {
                query?: {
                    /** @description Time window for the aggregation. */
                    window?: "24h" | "7d" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost share by model */
        get: {
            parameters: {
                query?: {
                    /** @description Time window for the aggregation. */
                    window?: "24h" | "7d" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsProviders"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the registered LLM providers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report which search backends the worker is configured to drive
         * @description Inspects deploy-time environment only (never spawns open-websearch or
         *     pings Tavily). `TAVILY_API_KEY` is reduced to a boolean and never
         *     echoed. The UI calls this once at boot to grey out unavailable toggles.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchCapabilities"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
            redis_ok?: boolean;
            postgres_ok?: boolean;
        };
        ProblemInput: {
            problem_text: string;
            /**
             * @default other
             * @enum {string}
             */
            competition_type: "mcm" | "icm" | "cumcm" | "huashu" | "other";
            attachments?: components["schemas"]["Attachment"][];
            /** @description Force a specific model; otherwise router picks per-agent defaults. */
            model_override?: string;
            /**
             * @description Cross-provider reasoning-effort hint. Translated in the gateway to
             *     each provider's native API: OpenAI-compat emits `reasoning_effort`
             *     + `reasoning.effort`; Anthropic emits
             *     `thinking.budget_tokens` (low=1024, medium=4096, high=16384).
             *     `off` suppresses emission entirely.
             *     Default `high`: this project targets MCM Outstanding / CUMCM 一等奖
             *     quality, so we trade extra latency + cost for better reasoning.
             * @default high
             * @enum {string}
             */
            reasoning_effort: "off" | "low" | "medium" | "high";
            /**
             * @description Opt-in to a 1M-token max_tokens ceiling for models that advertise
             *     long-context. When false, the worker caps at 20k (safe for all
             *     providers). Enable only for 1M-capable variants (Claude 3.5 Sonnet
             *     1M beta, Gemini 2.0, gpt-5-1m).
             * @default false
             */
            long_context: boolean;
            /**
             * @description Searcher routing override. When null (default), the worker uses its
             *     env-default config. Decoupled from `reasoning_effort` so a user can
             *     change source preference without touching model settings.
             */
            search_config?: components["schemas"]["SearchConfig"] | null;
        };
        /**
         * @description User-selectable retrieval routing for the Searcher agent. `primary`
         *     picks the first web source; `fallback_threshold` decides when the other
         *     source kicks in (unique-URL count below the threshold = fall back).
         *     `engines` only applies when open-webSearch is actually invoked.
         */
        SearchConfig: {
            /**
             * @default tavily
             * @enum {string}
             */
            primary: "tavily" | "open_websearch" | "none";
            /**
             * @default [
             *       "baidu",
             *       "csdn",
             *       "juejin",
             *       "duckduckgo"
             *     ]
             */
            engines: ("bing" | "baidu" | "duckduckgo" | "csdn" | "juejin" | "brave" | "exa" | "startpage")[];
            /**
             * @default basic
             * @enum {string}
             */
            tavily_depth: "basic" | "advanced";
            /** @default 3 */
            fallback_threshold: number;
        };
        Attachment: {
            name: string;
            /** @enum {string} */
            kind: "csv" | "xlsx" | "pdf" | "image" | "text";
            content_base64?: string;
        };
        RunCreated: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued";
        };
        Run: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            problem_text?: string;
            cost_rmb?: number;
            notebook_path?: string | null;
            paper_path?: string | null;
            events?: components["schemas"]["AgentEvent"][];
            /** @description True when more events exist past this page; re-request with `?after_seq=<next_after_seq>`. */
            has_more?: boolean;
            /** @description Cursor for the next page; the `seq` of the last event returned (null when the page is empty). */
            next_after_seq?: number | null;
        };
        RunSummary: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            problem_text?: string;
            competition_type?: string;
            cost_rmb?: number;
            notebook_path?: string | null;
            paper_path?: string | null;
        };
        RunList: {
            items: components["schemas"]["RunSummary"][];
        };
        FinetuneRequest: {
            message: string;
            /**
             * Format: uuid
             * @description Resume an existing fine-tune thread; omit to mint a new session.
             */
            session_id?: string | null;
        };
        FinetuneAccepted: {
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            session_id: string;
            /** @enum {string} */
            status: "queued";
        };
        CancelAccepted: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "cancel_signalled";
            /** @description True when an earlier POST already set the cancel flag (idempotent). */
            already_signalled: boolean;
        };
        StatsSummary: {
            window: string;
            total_runs: number;
            success_runs: number;
            failed_runs: number;
            success_rate: number;
            median_cost_rmb?: number | null;
            p95_latency_ms?: number | null;
        };
        StatsProviders: {
            window: string;
            total_cost_rmb: number;
            items: {
                model: string;
                cost_rmb: number;
                share_pct: number;
            }[];
        };
        ProviderList: {
            items: components["schemas"]["ProviderInfo"][];
        };
        ProviderInfo: {
            name: string;
            kind: string;
            models: string[];
            price_input_per_1m: number;
            price_output_per_1m: number;
            has_key: boolean;
        };
        SearchCapabilities: {
            tavily_available: boolean;
            open_websearch_available: boolean;
            available_engines: string[];
        };
        AgentEvent: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string|null} */
            agent?: "analyzer" | "modeler" | "coder" | "writer" | "critic" | "searcher" | "paper_editor" | "audit" | null;
            /** @enum {string} */
            kind: "stage.start" | "stage.done" | "log" | "token" | "cost" | "finetune.session.start" | "finetune.session.done" | "finetune.session.error" | "finetune.tool_call" | "finetune.tool_result" | "finetune.token" | "agent.output" | "kernel.stdout" | "kernel.figure" | "kernel.error" | "error" | "done";
            seq: number;
            /** Format: date-time */
            ts: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        ChatCompletionRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            /** @default 0.2 */
            temperature: number;
            max_tokens?: number;
            /** @default false */
            stream: boolean;
            response_format?: {
                [key: string]: unknown;
            };
            /**
             * @description Optional reasoning-effort hint. Gateway translates it per provider:
             *     OpenAI-compat bodies get `reasoning_effort` and
             *     `reasoning.effort` set; Anthropic bodies get
             *     `thinking.budget_tokens` (low=1024, medium=4096, high=16384) plus a
             *     conditional `max_tokens` bump. `off` or unset omits emission.
             * @enum {string}
             */
            reasoning_effort?: "off" | "low" | "medium" | "high";
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content: string;
            name?: string;
            /**
             * @description Mark this message as an Anthropic prompt-cache break point. When
             *     true, the gateway emits `cache_control: { "type": "ephemeral" }`
             *     on the message (Anthropic native: as a content-block attribute;
             *     OpenAI-compat: as an extra message-level key for Claude-backed
             *     proxies). The cached prefix runs from the start of the request
             *     through this message; Anthropic supports up to 4 breakpoints per
             *     request, but v1 of this wiring uses exactly one. Silently
             *     ignored by providers that don't support prompt caching.
             * @default false
             */
            cache_breakpoint: boolean;
        };
        ChatCompletionResponse: {
            id: string;
            model: string;
            created?: number;
            choices: {
                index?: number;
                message?: components["schemas"]["ChatMessage"];
                finish_reason?: string;
            }[];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
